name: Deploy Astro to Netlify

on:
  push:
    branches:
      - main # Change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Change if necessary

      - name: Install Dependencies
        run: npm install --legacy-peer-deps # Use `pnpm install` or `yarn install` if applicable

      - name: Build Astro Site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=dist --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
